baseURL = 'https://thedevdiary.me/'
languageCode = 'en-us'
title = 'Dev Diary'
theme="nightfall"


[menu]
  [[menu.header]]
    name = "blog"
    weight = 2
    url = "blog/"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"
  [[menu.header]]
    name = "bookshelf"
    weight = 3
    url = "/bookshelf"

[params]
author = "The Dev Diary"
user = "dev"
hostname = "diary"

readingTime = false  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "Github"
url = "https://github.com/sum28it"
icon = "svg/icons8-github.svg"

[[params.social]]
key = 1
name = "Linkedin"
url = "https://www.linkedin.com/in/sumit-kumar-prasad-569728189/"
icon = "svg/icons8-linkedin-logo.svg"


[[params.social]]
key = 2
name = "Email"
url = "mailto:prasad28sumit@gmail.com"
icon = "svg/icons8-gmail.svg"



